### PR TITLE
Added support for Django 3.0 and Python 3.8

### PR DESCRIPTION
**Pull request by avallbona**
* added support for Django 3.0
* added support for Python 3.8
* fixed style enviroment
* fixed setup.py
* added python and django versions badges on README.md
* added more verbosity to tests
* removed unnecessary code `test_manage.py`

### CODE REVIEW

**Comment by avallbona** [comment]
You're very welcome!!! :+1:

**Comment by avallbona** [comment]
In order to have the new added badges updated you will need to make a release of the package.

**Comment by tim-schilling** [comment]
Looks like there's a section in the README that was missed regarding the supported django and python versions: https://github.com/raphaelm/django-scopes/pull/16/files#diff-04c6e90faac2675aa89e2176d2eec7d8L37

**Comment by avallbona** [comment]
> Looks like there's a section in the README that was missed regarding the supported django and python versions: https://github.com/raphaelm/django-scopes/pull/16/files#diff-04c6e90faac2675aa89e2176d2eec7d8L37

addressed with this pr https://github.com/raphaelm/django-scopes/pull/18 👍

**Pull request merged**
